CC = g++

lambda_01:lambda_01.o
	${CC} -o lambda_01 lambda_01.o 
	./lambda_01
lambda_01.o:lambda_01.cpp
	${CC} -c lambda_01.cpp

lambda_02:lambda_02.o
	${CC} -o lambda_02 lambda_02.o
	./lambda_02
lambda_02.o:lambda_02.cpp
	${CC} -c lambda_02.cpp